### ISSUE TITLE
Wrong contamination estimates

### ISSUE THREAD

**Issue by gevro** [mtdna/haplochecker#2]
Hi, I'm running haplochecker as part of the new Broad GATK Mitochondrial analysis pipeline that uses it in order to estimate contamination.

However, when running it on regular whole genome sequencing data, it is giving illogical contamination estimates:

SampleID	Contamination	MinorHG	MinorLevel	MinorSNPs	MinorHGvariants	MajorHG	MajorLevel	MajorSNPs	MajorHGvariants	VerifyScore	meanCovVar	HG_Distance
UDP-1003_genome.realigned.bam	None	U8b1b2	0.988	24/30	3	U8b1b2	0.000	24/30	1	0.0	3260.0	0

It is showing the MinorHG as being at a level of 0.988 an the Major HG at a level of 0.0. Also, it is showing the Major and Minor HG as being the same. Must be a few bugs in haplochecker...

**Comment by seppinho** [comment]
hi gevro. sorry for the confusion, latest release is available here:
http://github.com/genepi/haplocheck

**Comment by gevro** [comment]
Thanks. What would be the equivalent command to this?
java -jar mitolib-0.1.0.jar haplochecker

I don't see haplochecker specifically in the above respository. Is haplocheck the same thing as haplochecker? How do I install and run it locally?

Also, do you have a dockerized version of it?

**Comment by gevro** [comment]
Nevermind, I actually managed to make a dockerized version of the new haplocheck. I have some questions about it, so I will post it on that repository. Thanks.
